---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: git://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: "^.*vault.yml$"
  - repo: git://github.com/awslabs/cfn-python-lint
    rev: v0.58.0
    hooks:
      - id: cfn-python-lint
        files: \.template$
  - repo: https://github.com/amperser/proselint.git
    rev: 0.13.0
    hooks:
      - id: proselint
        files: \.md$
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
