---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/detailyang/pre-commit-shell.git
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.36.2
    hooks:
      - id: yamllint
        exclude: "^.*vault.yml$"
  - repo: https://github.com/awslabs/cfn-python-lint.git
    rev: v1.30.0
    hooks:
      - id: cfn-python-lint
        files: \.template$
  - repo: https://github.com/amperser/proselint.git
    rev: 0.14.0
    hooks:
      - id: proselint
        files: \.md$
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.382
    hooks:
      - id: checkov_container
        args: [--quiet]
